export const TSP = {
  NEAREST_NEIGHBOUR: 'NEAREST_NEIGHBOUR',
  NEAREST_INSERTION: 'NEAREST_INSERTION',
  CHEAPEST_INSERTION: 'CHEAPEST_INSERTION',
  FARTHEST_INSERTION: 'FARTHEST_INSERTION',
  RANDOM_INSERTION: 'RANDOM_INSERTION',
  CONVEX_HULL: 'CONVEX_HULL',
  TWO_OPT: 'TWO_OPT',
  BACKTRACKING: 'BACKTRACKING',
};
